"""
regions.py — Suburb knowledge base for the SEQ / QLD property pipeline.
Fast 50: 50 high-growth QLD suburbs targeted by the weekly scheduled scrape.
"""

ZONING: dict[str, dict] = {
    "Woodridge":       {"council": "Logan City Council",     "zone": "Low Density Res / Centre Zone",        "notes": "Train station precinct. Centre zone near Woodridge station. High MDR potential."},
    "Kingston":        {"council": "Logan City Council",     "zone": "Low Density Res / Centre Zone",        "notes": "Urban core of Logan. Centre zone, MDR pockets near transit."},
    "Logan Central":   {"council": "Logan City Council",     "zone": "Low Density Res / Centre Zone",        "notes": "Logan CBD fringe. Centre zone, high MDR potential."},
    "Marsden":         {"council": "Logan City Council",     "zone": "Low Density Res / MDR",                "notes": "Infill suburb. MDR zoning along key corridors."},
    "Browns Plains":   {"council": "Logan City Council",     "zone": "Low Density Res / Centre Zone",        "notes": "Major retail hub. Some MDR along Grand Plaza corridor."},
    "Beenleigh":       {"council": "Logan City Council",     "zone": "Low Density Res / Centre Zone",        "notes": "Centre zone, train line. ShapingSEQ growth node. High MDR potential."},
    "Slacks Creek":    {"council": "Logan City Council",     "zone": "Low Density Residential",              "notes": "Established suburb. Some MDR pockets near main roads."},
    "Meadowbrook":     {"council": "Logan City Council",     "zone": "Low Density Residential",              "notes": "Near Logan Hospital and TAFE. Rental demand high."},
    "Bethania":        {"council": "Logan City Council",     "zone": "Low Density Residential",              "notes": "Near Beenleigh. Train station suburb. Rental demand."},
    "Regents Park":    {"council": "Logan City Council",     "zone": "Low Density Residential",              "notes": "Established suburb. Close to train line."},
    "Underwood":       {"council": "Logan City Council",     "zone": "Low Density Res / Mixed Use",          "notes": "Corridor suburb. Some mixed-use and MDR pockets."},
    "Springwood":      {"council": "Logan City Council",     "zone": "Low Density Res / Mixed Use",          "notes": "Major commercial hub. MDR and mixed use pockets."},
    "Crestmead":       {"council": "Logan City Council",     "zone": "Low Density Residential",              "notes": "Growth suburb. Industrial fringe. Rental demand."},
    "Eagleby":         {"council": "Logan City Council",     "zone": "Low Density Residential",              "notes": "Near Beenleigh CBD. Affordable. Rental demand."},
    "Ipswich":         {"council": "Ipswich City Council",   "zone": "Low Density Res / Inner Urban",        "notes": "MDR / Centre Zone potential near CBD. ShapingSEQ corridor."},
    "Leichhardt":      {"council": "Ipswich City Council",   "zone": "Low Density Residential",              "notes": "Inner suburb adj to Ipswich CBD. Rezone upside likely."},
    "Redbank Plains":  {"council": "Ipswich City Council",   "zone": "Low Density Res / Emerging Community", "notes": "Fast-growing suburb. Emerging community zones at fringe."},
    "Ripley":          {"council": "Ipswich City Council",   "zone": "Emerging Community / PDA",             "notes": "Ripley Valley Priority Development Area. Greenfield master-planned."},
    "Springfield":     {"council": "Ipswich City Council",   "zone": "Low Density Res / Mixed Use",          "notes": "Springfield Lakes / Orion corridor. Centre zone near retail hub."},
    "Brassall":        {"council": "Ipswich City Council",   "zone": "Low Density Residential",              "notes": "Growth suburb west of CBD. Some MDR pockets."},
    "East Ipswich":    {"council": "Ipswich City Council",   "zone": "Low Density Residential",              "notes": "Heritage precinct. Limited rezone but large blocks."},
    "Lowood":          {"council": "Ipswich City Council",   "zone": "Low Density Residential",              "notes": "Small township in Lockyer Valley corridor. Affordable land."},
    "Plainland":       {"council": "Ipswich City Council",   "zone": "Low Density Res / Growth Corridor",    "notes": "Lockyer Valley growth corridor. Close to Gatton and Ipswich."},
    "Caboolture":      {"council": "Moreton Bay Regional",   "zone": "Low Density Res / Centre Zone",        "notes": "Centre zone near CBD. MDR in inner ring. ShapingSEQ growth node."},
    "Morayfield":      {"council": "Moreton Bay Regional",   "zone": "Low Density Res / MDR",                "notes": "Fast 50 suburb. Active MDR and Centre zone pockets. High growth."},
    "North Lakes":     {"council": "Moreton Bay Regional",   "zone": "Low Density Res / Mixed Use",          "notes": "Master-planned community. Strong retail and employment node."},
    "Mango Hill":      {"council": "Moreton Bay Regional",   "zone": "Low Density Residential",              "notes": "Near North Lakes. Rail corridor. Rapid population growth."},
    "Narangba":        {"council": "Moreton Bay Regional",   "zone": "Low Density Residential",              "notes": "Train station suburb. Affordable. Strong rental demand."},
    "Burpengary":      {"council": "Moreton Bay Regional",   "zone": "Low Density Residential",              "notes": "Growth suburb near Caboolture corridor. Affordable land."},
    "Griffin":         {"council": "Moreton Bay Regional",   "zone": "Low Density Res / Growth Corridor",    "notes": "Newer growth suburb near North Lakes. Land release area."},
    "Kallangur":       {"council": "Moreton Bay Regional",   "zone": "Low Density Residential",              "notes": "Near Petrie university campus. Rail access. Affordable."},
    "Petrie":          {"council": "Moreton Bay Regional",   "zone": "Low Density Res / Centre Zone",        "notes": "University of Sunshine Coast campus. Rail. Rezone potential near station."},
    "Bray Park":       {"council": "Moreton Bay Regional",   "zone": "Low Density Residential",              "notes": "Established suburb. Strathpine rail. Affordable."},
    "Chermside":       {"council": "Brisbane City Council",  "zone": "Low Density Res / Centre Zone",        "notes": "Major centre zone. Bus station. ShapingSEQ priority activity centre."},
    "Wavell Heights":  {"council": "Brisbane City Council",  "zone": "Low Density Residential",              "notes": "Inner north. Established. Duplex/townhouse infill opportunity."},
    "Zillmere":        {"council": "Brisbane City Council",  "zone": "Low Density Residential",              "notes": "Northern corridor. Affordable. Near rail. Infill upside."},
    "Acacia Ridge":    {"council": "Brisbane City Council",  "zone": "Low Density Res / Industrial Fringe",  "notes": "South Brisbane industrial corridor. Affordable. Renter demand."},
    "Oxley":           {"council": "Brisbane City Council",  "zone": "Low Density Residential",              "notes": "Southwest rail corridor. Near Darra industrial. Duplex potential."},
    "Yeronga":         {"council": "Brisbane City Council",  "zone": "Low Density Res / MDR",                "notes": "Inner-south. MDR pockets. University of QLD catchment."},
    "Herston":         {"council": "Brisbane City Council",  "zone": "Low Density Res / Health Precinct",    "notes": "Adjacent to RBWH. Health sector employment. High rental demand."},
    "Caloundra":       {"council": "Sunshine Coast Council", "zone": "Low Density Res / Centre Zone",        "notes": "Coastal gateway. Centre zone near CBD. Redevelopment potential."},
    "Nambour":         {"council": "Sunshine Coast Council", "zone": "Low Density Res / Centre Zone",        "notes": "Hinterland town. Rail. Affordable. Rezone potential near station."},
    "Toowoomba":       {"council": "Toowoomba Regional",     "zone": "Low Density Res / Centre Zone",        "notes": "Second-largest inland city. Strong owner-occupier and investor demand."},
    "Highfields":      {"council": "Toowoomba Regional",     "zone": "Low Density Res / Growth Corridor",    "notes": "Fastest-growing suburb in Toowoomba region. New estates."},
    "Townsville":      {"council": "Townsville City Council","zone": "Low Density Res / Centre Zone",        "notes": "North QLD regional capital. Defence, health, university employment."},
    "Bohle Plains":    {"council": "Townsville City Council","zone": "Low Density Res / Growth Corridor",    "notes": "Growth suburb near Townsville industrial estate. Affordable."},
    "Mackay":          {"council": "Mackay Regional",        "zone": "Low Density Res / Centre Zone",        "notes": "Resource-sector city. Yields elevated by mining/resource wages."},
    "Ooralea":         {"council": "Mackay Regional",        "zone": "Low Density Residential",              "notes": "Established Mackay suburb. Affordable. Near industrial zone."},
    "Frenchville":     {"council": "Rockhampton Regional",   "zone": "Low Density Residential",              "notes": "Affluent Rockhampton suburb. Stable demand."},
    "Norman Gardens":  {"council": "Rockhampton Regional",   "zone": "Low Density Residential",              "notes": "Popular family suburb in Rockhampton. Steady growth."},
    "Gracemere":       {"council": "Rockhampton Regional",   "zone": "Low Density Res / Growth Corridor",    "notes": "Fastest-growing suburb in CQ. Industrial and residential expansion."},
    "Koongal":         {"council": "Rockhampton Regional",   "zone": "Low Density Residential",              "notes": "Near Rockhampton CBD. Affordable investor market."},
    "Park Avenue":     {"council": "Rockhampton Regional",   "zone": "Low Density Residential",              "notes": "Mid-ring Rockhampton. Family suburb. Stable yields."},
    "Gladstone":       {"council": "Gladstone Regional",     "zone": "Low Density Res / Centre Zone",        "notes": "Port and industrial city. Resource-sector employment. Elevated yields."},
    "Kepnock":         {"council": "Bundaberg Regional",     "zone": "Low Density Residential",              "notes": "Established Bundaberg suburb. Near hospital. Rental demand."},
    "Avenell Heights": {"council": "Bundaberg Regional",     "zone": "Low Density Residential",              "notes": "Bundaberg growth suburb. Near hospital and schools."},
    "Walkervale":      {"council": "Bundaberg Regional",     "zone": "Low Density Residential",              "notes": "Bundaberg suburb. Affordable. Rental market active."},
    "Hervey Bay":      {"council": "Fraser Coast Regional",  "zone": "Low Density Res / Coastal Growth",     "notes": "Fastest-growing coastal city in QLD. Retiree and lifestyle market."},
    "Maryborough":     {"council": "Fraser Coast Regional",  "zone": "Low Density Res / Centre Zone",        "notes": "Heritage city. Affordable. Rail. Service-sector employment."},
    "Kingaroy":        {"council": "South Burnett Regional", "zone": "Low Density Res / Centre Zone",        "notes": "Regional service town. Affordable yields. Stable rental base."},
}

REZONE_POTENTIAL: dict[str, str] = {
    "Woodridge":       "HIGH - Centre zone, MDR ring, transit precinct",
    "Kingston":        "HIGH - Urban core, centre zone, MDR pockets",
    "Logan Central":   "HIGH - Logan CBD fringe, centre zone",
    "Beenleigh":       "HIGH - Centre zone, train line, ShapingSEQ growth node",
    "Browns Plains":   "MEDIUM-HIGH - Centre zone near Grand Plaza",
    "Springwood":      "MEDIUM-HIGH - Mixed use, MDR pockets, commercial hub",
    "Marsden":         "MEDIUM - MDR corridors, infill opportunity",
    "Slacks Creek":    "MEDIUM - MDR pockets along main roads",
    "Meadowbrook":     "MEDIUM - Near Logan Hospital, rental demand",
    "Bethania":        "MEDIUM - Train station suburb, rental demand",
    "Regents Park":    "MEDIUM - Close to train line, infill",
    "Underwood":       "MEDIUM - Mixed use and MDR pockets",
    "Crestmead":       "LOW-MEDIUM - Growth suburb, rental demand",
    "Eagleby":         "LOW-MEDIUM - Near Beenleigh, affordable",
    "Ipswich":         "HIGH - Inner city, ShapingSEQ corridor",
    "Leichhardt":      "HIGH - Adj CBD, character precinct",
    "Redbank Plains":  "MEDIUM - Growing, emerging community",
    "Ripley":          "MEDIUM - PDA greenfield, master-planned",
    "Springfield":     "MEDIUM - Mixed use, centre zone near Orion",
    "East Ipswich":    "MEDIUM - Large blocks, heritage area",
    "Lowood":          "LOW-MEDIUM - Small town, Lockyer corridor",
    "Plainland":       "LOW-MEDIUM - Growth corridor, emerging community",
    "Caboolture":      "HIGH - Centre zone, MDR ring, ShapingSEQ node",
    "Morayfield":      "HIGH - Fast 50, MDR pockets, active growth",
    "North Lakes":     "MEDIUM-HIGH - Master-planned, retail/employment node",
    "Mango Hill":      "MEDIUM - Near rail, strong population growth",
    "Narangba":        "MEDIUM - Train station, affordable, rental demand",
    "Burpengary":      "LOW-MEDIUM - Growth corridor, affordable",
    "Griffin":         "LOW-MEDIUM - New growth suburb, land release",
    "Kallangur":       "MEDIUM - Near USC Petrie campus, rail access",
    "Petrie":          "MEDIUM-HIGH - USC campus, train, rezone near station",
    "Bray Park":       "LOW-MEDIUM - Established, rail access, affordable",
    "Chermside":       "HIGH - Priority activity centre, major bus hub",
    "Wavell Heights":  "MEDIUM - Duplex/townhouse infill, inner north",
    "Zillmere":        "MEDIUM - Rail corridor, northern suburbs growth",
    "Acacia Ridge":    "MEDIUM - Industrial fringe, affordable, renter demand",
    "Oxley":           "MEDIUM - Rail corridor, duplex potential, affordable",
    "Yeronga":         "HIGH - MDR pockets, inner-south, UQ catchment",
    "Herston":         "HIGH - Health precinct, rental demand, RBWH adj",
    "Caloundra":       "MEDIUM-HIGH - Coastal gateway, centre zone, redevelopment",
    "Nambour":         "MEDIUM - Rail access, affordable, rezone near station",
    "Toowoomba":       "MEDIUM - Strong regional city, centre zone, infill",
    "Highfields":      "LOW-MEDIUM - Growth corridor, new estates",
    "Townsville":      "MEDIUM - Regional capital, centre zone, defence/health",
    "Bohle Plains":    "LOW-MEDIUM - Growth corridor, near industrial estate",
    "Mackay":          "MEDIUM - Resource-sector demand, centre zone",
    "Ooralea":         "LOW-MEDIUM - Established, near industrial, affordable",
    "Frenchville":     "LOW-MEDIUM - Stable established suburb",
    "Norman Gardens":  "LOW-MEDIUM - Family suburb, steady growth",
    "Gracemere":       "MEDIUM - Fastest-growing CQ suburb, industrial/res",
    "Koongal":         "LOW-MEDIUM - Affordable, near CBD",
    "Park Avenue":     "LOW-MEDIUM - Mid-ring, stable yields",
    "Gladstone":       "MEDIUM - Port city, resource sector, elevated yields",
    "Kepnock":         "LOW-MEDIUM - Near hospital, rental demand",
    "Avenell Heights": "LOW-MEDIUM - Near hospital and schools",
    "Walkervale":      "LOW - Affordable, stable rental market",
    "Hervey Bay":      "MEDIUM - Coastal growth, lifestyle demand, retiree market",
    "Maryborough":     "LOW-MEDIUM - Heritage town, rail, affordable",
    "Kingaroy":        "LOW-MEDIUM - Regional service town, stable yields",
}

HIGH_REZONE = {
    "Woodridge", "Kingston", "Logan Central", "Beenleigh",
    "Ipswich", "Leichhardt",
    "Morayfield", "Caboolture",
    "Chermside", "Yeronga", "Herston",
}

MEDIUM_REZONE = {
    "Browns Plains", "Springwood", "Marsden", "Slacks Creek",
    "Meadowbrook", "Bethania", "Regents Park", "Underwood",
    "East Ipswich", "Redbank Plains", "Brassall", "Ripley", "Springfield",
    "North Lakes", "Mango Hill", "Narangba", "Kallangur", "Petrie",
    "Wavell Heights", "Zillmere", "Acacia Ridge", "Oxley",
    "Caloundra", "Nambour", "Toowoomba", "Mackay", "Gracemere", "Hervey Bay",
}

CASHFLOW_DEMAND_SUBURBS = {
    "Meadowbrook", "Herston", "Kepnock", "Avenell Heights",
    "Kallangur", "Petrie", "Yeronga",
    "Townsville", "Mackay",
    "Logan Central", "Woodridge", "Kingston",
}

FAST_50 = {
    "Beenleigh", "Browns Plains", "Kingston", "Logan Central",
    "Marsden", "Woodridge", "Acacia Ridge", "Oxley", "Yeronga",
    "Ipswich", "Leichhardt", "Redbank Plains", "Ripley", "Springfield",
    "Lowood", "Plainland",
    "Caboolture", "Morayfield", "Burpengary", "Narangba",
    "North Lakes", "Mango Hill", "Griffin", "Kallangur",
    "Petrie", "Bray Park",
    "Chermside", "Wavell Heights", "Zillmere", "Herston",
    "Caloundra", "Nambour",
    "Toowoomba", "Highfields",
    "Townsville", "Bohle Plains",
    "Mackay", "Ooralea",
    "Gracemere", "Frenchville", "Norman Gardens", "Koongal", "Park Avenue",
    "Gladstone",
    "Kepnock", "Avenell Heights", "Walkervale",
    "Hervey Bay", "Maryborough",
    "Kingaroy",
}

DEFAULT_ZONE = {
    "council": "Unknown",
    "zone":    "Low Density Residential",
    "notes":   "No zoning data - scored using defaults.",
}
